---
title: "ShinyForm"
author: "Doris"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(shiny)
library(shinyreforms)
```



```{r echo=FALSE}

antiepileptiques <- c(
  "Depakine 300 mg (comprimés à libération prolongée)",
  "Depakine Chrono 500 mg (comprimés à libération prolongée)",
  "Depakine Chrono 750 mg (comprimés à libération prolongée)",
  "Depakine Chrono 1000 mg (comprimés à libération prolongée)",
  "Tegretol 200 mg (comprimés)",
  "Tegretol 400 mg (comprimés à libération prolongée)"
)

myForm <- shinyreforms::ShinyForm$new(
    "myForm",
    submit = "Submit",
    onSuccess = function(self, input, output) {
        yourName <- self$getValue(input, "name_input")
        dosage <- self$getValue(input, "antiepileptique")
  
        output$result <- shiny::renderText({
            paste0("Your name is ", yourName, "!", dosage)
        })
        
    },
    onError = function(self, input, output) {
        output$result <- shiny::renderText({
            "Form is invalid!"
        })
    },
    shinyreforms::validatedInput(
        shiny::textInput("name_input", label = "Username"),
        helpText="Username length is between 4 and 12 characters.",
        #validators = c(
            #shinyreforms::ValidatorMinLength(4),
            #shinyreforms::ValidatorMaxLength(12),
            #shinyreforms::Validator$new(
                #test = function(value) value != "test",
                #failMessage = "Username can't be 'test'!"
            #)
        #)
    ),
    shiny::selectInput(
      "antiepileptique",
      label = "Choisissez le médicament avec le dosage qui vous ai prescrit:",
      choices = antiepileptiques,
      selected = NULL
    ),
    shinyreforms::validatedInput(
        shiny::checkboxInput("checkbox", label = "I accept!"),
        validators = c(
            shinyreforms::ValidatorRequired()
        )
    )
)



```

```{r echo=FALSE}

ui <- shiny::bootstrapPage(
    shinyreforms::shinyReformsPage(  # This adds a dependency on shinyreforms .css
        shiny::fluidPage(
            shiny::tags$h1("Example ShinyForm!"),
            myForm$ui(),  # <- ShinyForm will be included here!
            shiny::tags$h4("Result:"),
            shiny::textOutput("result")
        )
    )
)

server <- function(input, output, session) {
    myForm$server(input, output)
    
    # More server logic
  
    
    
}

shiny::shinyApp(ui = ui, server = server)

```